import json

with open("knowledge/feature_metadata.json", "r") as f:
    data = json.load(f)

missing = [
    "Identity Consistency",
    "Credit Inquiry Frequency",
    "Address Volatility",
    "Device ID Change",
    "Time of Day Deviation",
    "Inbound/Outbound Ratio",
    "Counterparty Diversity"
]

start_id = 9000
for i, concept in enumerate(missing):
    fid = f"F{start_id + i}"
    data["feature_mapping"][fid] = {
        "concept": concept,
        "description": f"Autogenerated description for {concept}",
        "direction_meaning": {
            "positive": "Higher than expected",
            "negative": "Lower than expected"
        }
    }

with open("knowledge/feature_metadata.json", "w") as f:
    json.dump(data, f, indent=2)
